export interface Teacher {
  // From User base class
  id: string;
  email: string;
  first_name: string;
  last_name: string;
  phone_number?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;

  // Teacher-specific fields
  employee_id: string; // Will be auto-generated by backend
  department?: string;
  qualification?: string;
  joining_date?: string; // ISO date string
  is_class_teacher: boolean;

  // Personal info
  address?: string;
  city?: string;
  county?: string;
  country?: string;
  gender?: string;
  whatsapp_number?: string;

  // Status fields
  status: 'active' | 'inactive' | 'retired' | 'resigned';
  exit_date?: string; // ISO date string
  retirement_date?: string; // ISO date string
  resignation_date?: string; // ISO date string
  resignation_reason?: string;
}

export interface TeacherCreate {
  // Required fields
  email: string;
  first_name: string;
  last_name: string;
  employee_id?: string;

  // Optional fields
  phone_number?: string;
  department?: string;
  qualification?: string;
  joining_date?: string;
  is_class_teacher?: boolean;
  address?: string;
  city?: string;
  county?: string;
  country?: string;
  gender?: string;
  whatsapp_number?: string;
}

export interface TeacherUpdate {
  email?: string;
  password?: string;
  first_name?: string;
  last_name?: string;
  phone_number?: string;
  department?: string;
  qualification?: string;
  joining_date?: string;
  is_class_teacher?: boolean;
  address?: string;
  city?: string;
  county?: string;
  country?: string;
  gender?: string;
  whatsapp_number?: string;
  status?: 'active' | 'inactive' | 'retired' | 'resigned';
  resignation_reason?: string;
}

export interface TeacherFilters {
  department?: string;
  status?: 'all' | 'active' | 'inactive' | 'retired' | 'resigned';
  is_class_teacher?: boolean;
  search?: string;
}

export interface ClassTeacher extends Teacher {
  is_class_teacher: true;
}

export interface TeacherCreateResponse extends Teacher {
  generated_password?: string;
}