"""
add_class_enrollment_and_update_relationships

Revision ID: 041b5de2aac8
Revises: b8f3abdb7e10
Create Date: 2025-09-17 19:06:18.752966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041b5de2aac8'
down_revision = 'b8f3abdb7e10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('enrollments_grade_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'academic_grades', ['grade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_grade_id_fkey'), 'enrollments', 'grades', ['grade_id'], ['id'])
    # ### end Alembic commands ###