"""
add_tenant_notification_config

Revision ID: 1c7b301788e8
Revises: 89ae21af15ae
Create Date: 2025-08-11 22:37:38.219821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7b301788e8'
down_revision = '89ae21af15ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###