"""
create_tenant_notification_configs_table_with_uuid

Revision ID: 30940129a01c
Revises: 1c7b301788e8
Create Date: 2025-08-12 11:20:54.176446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30940129a01c'
down_revision = '1c7b301788e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_notification_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
    sa.Column('admin_whatsapp_number', sa.String(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('teacher_welcome_template', sa.Text(), nullable=True),
    sa.Column('student_welcome_template', sa.Text(), nullable=True),
    sa.Column('parent_welcome_template', sa.Text(), nullable=True),
    sa.Column('notify_admin_on_user_creation', sa.Boolean(), nullable=True),
    sa.Column('notify_parents_on_student_creation', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_notification_configs')
    # ### end Alembic commands ###