"""
increase_academic_year_name_length

Revision ID: 39184320e931
Revises: bafc311a4bfc
Create Date: 2025-08-28 12:26:20.622735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39184320e931'
down_revision = 'bafc311a4bfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_years', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_years', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###