"""
add_students_photo_column

Revision ID: 42ae52118fde
Revises: 0423f3706821
Create Date: 2026-01-27 02:38:36.538493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42ae52118fde'
down_revision = '0423f3706821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('photo', sa.String(length=500), nullable=True, comment='URL to student profile photo'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'photo')
    # ### end Alembic commands ###