"""
add_address_field_to_user

Revision ID: 85af8a038e9d
Revises: 2a299b032478
Create Date: 2025-07-15 10:42:16.111316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85af8a038e9d'
down_revision = '2a299b032478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_tenant_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_constraint(op.f('activity_logs_user_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'])
    op.alter_column('enrollments', 'grade',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('enrollments', 'withdrawal_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_super_admin_activity_logs_action'), table_name='super_admin_activity_logs')
    op.drop_index(op.f('ix_super_admin_activity_logs_created_at'), table_name='super_admin_activity_logs')
    op.drop_index(op.f('ix_super_admin_activity_logs_entity_type'), table_name='super_admin_activity_logs')
    op.drop_index(op.f('ix_super_admin_activity_logs_target_tenant_id'), table_name='super_admin_activity_logs')
    op.drop_index(op.f('ix_super_admin_activity_logs_user_id'), table_name='super_admin_activity_logs')
    op.drop_constraint(op.f('super_admin_activity_logs_user_id_fkey'), 'super_admin_activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'super_admin_activity_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'super_admin_activity_logs', 'tenants', ['target_tenant_id'], ['id'])
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=False)
    op.drop_constraint(None, 'super_admin_activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'super_admin_activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('super_admin_activity_logs_user_id_fkey'), 'super_admin_activity_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_super_admin_activity_logs_user_id'), 'super_admin_activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_super_admin_activity_logs_target_tenant_id'), 'super_admin_activity_logs', ['target_tenant_id'], unique=False)
    op.create_index(op.f('ix_super_admin_activity_logs_entity_type'), 'super_admin_activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_super_admin_activity_logs_created_at'), 'super_admin_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_super_admin_activity_logs_action'), 'super_admin_activity_logs', ['action'], unique=False)
    op.alter_column('enrollments', 'withdrawal_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('enrollments', 'grade',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_user_id_fkey'), 'activity_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_tenant_id'), 'activity_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    # ### end Alembic commands ###