"""
add_tenant_id_to_existing_tables

Revision ID: 89ae21af15ae
Revises: 85af8a038e9d
Create Date: 2025-07-19 13:25:58.505000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ae21af15ae'
down_revision = '85af8a038e9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_grades', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_academic_grades_tenant_id'), 'academic_grades', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'academic_grades', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('academic_years', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_academic_years_tenant_id'), 'academic_years', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'academic_years', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_activity_logs_tenant_id'), 'activity_logs', ['tenant_id'], unique=False)
    op.add_column('announcements', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_announcements_tenant_id'), 'announcements', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'announcements', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('assignments', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_assignments_tenant_id'), 'assignments', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'assignments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('classes', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_classes_tenant_id'), 'classes', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'classes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('enrollments', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_enrollments_tenant_id'), 'enrollments', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'enrollments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'events', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('exams', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_exams_tenant_id'), 'exams', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'exams', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('feedbacks', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_feedbacks_tenant_id'), 'feedbacks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'feedbacks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('grades', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_grades_tenant_id'), 'grades', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'grades', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('schedules', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_schedules_tenant_id'), 'schedules', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'schedules', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('sections', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_sections_tenant_id'), 'sections', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'sections', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('subjects', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_subjects_tenant_id'), 'subjects', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'subjects', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('timetables', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_timetables_tenant_id'), 'timetables', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'timetables', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    op.drop_index(op.f('ix_timetables_tenant_id'), table_name='timetables')
    op.drop_column('timetables', 'tenant_id')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_tenant_id'), table_name='subjects')
    op.drop_column('subjects', 'tenant_id')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_index(op.f('ix_sections_tenant_id'), table_name='sections')
    op.drop_column('sections', 'tenant_id')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_index(op.f('ix_schedules_tenant_id'), table_name='schedules')
    op.drop_column('schedules', 'tenant_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_column('messages', 'tenant_id')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_index(op.f('ix_grades_tenant_id'), table_name='grades')
    op.drop_column('grades', 'tenant_id')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_index(op.f('ix_feedbacks_tenant_id'), table_name='feedbacks')
    op.drop_column('feedbacks', 'tenant_id')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_index(op.f('ix_exams_tenant_id'), table_name='exams')
    op.drop_column('exams', 'tenant_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_column('events', 'tenant_id')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_index(op.f('ix_enrollments_tenant_id'), table_name='enrollments')
    op.drop_column('enrollments', 'tenant_id')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_index(op.f('ix_classes_tenant_id'), table_name='classes')
    op.drop_column('classes', 'tenant_id')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_index(op.f('ix_assignments_tenant_id'), table_name='assignments')
    op.drop_column('assignments', 'tenant_id')
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_index(op.f('ix_announcements_tenant_id'), table_name='announcements')
    op.drop_column('announcements', 'tenant_id')
    op.drop_index(op.f('ix_activity_logs_tenant_id'), table_name='activity_logs')
    op.drop_constraint(None, 'academic_years', type_='foreignkey')
    op.drop_index(op.f('ix_academic_years_tenant_id'), table_name='academic_years')
    op.drop_column('academic_years', 'tenant_id')
    op.drop_constraint(None, 'academic_grades', type_='foreignkey')
    op.drop_index(op.f('ix_academic_grades_tenant_id'), table_name='academic_grades')
    op.drop_column('academic_grades', 'tenant_id')
    # ### end Alembic commands ###