"""
add_class_enrollment_and_update_relationships

Revision ID: 935e7ab6a608
Revises: 041b5de2aac8
Create Date: 2025-09-17 19:14:55.044896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935e7ab6a608'
down_revision = '041b5de2aac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###