"""
attendance_model update-foreignkey

Revision ID: 9fba10beddbd
Revises: 58533a569373
Create Date: 2025-08-28 16:41:54.186372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fba10beddbd'
down_revision = '58533a569373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###