"""
add_academic_year_and_enhance_enrollment_with_semesters

Revision ID: b3d55459d588
Revises: f7sadvgfiu768
Create Date: 2025-07-10 15:12:24.322193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3d55459d588'
down_revision = 'f7sadvgfiu768'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_semester', sa.Integer(), nullable=True),
    sa.Column('semester_1_start', sa.Date(), nullable=False),
    sa.Column('semester_1_end', sa.Date(), nullable=False),
    sa.Column('semester_2_start', sa.Date(), nullable=False),
    sa.Column('semester_2_end', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # REMOVE THESE LINES - they are causing the error:
    # op.drop_table('activity_logs')
    # op.drop_table('resources')
    # op.drop_table('tenant_settings')
    # op.drop_table('tenants')
    
    op.add_column('enrollments', sa.Column('academic_year_id', sa.UUID(), nullable=True))
    op.add_column('enrollments', sa.Column('semester', sa.Integer(), nullable=False))
    op.add_column('enrollments', sa.Column('semester_1_status', sa.String(length=20), nullable=True))
    op.add_column('enrollments', sa.Column('semester_2_status', sa.String(length=20), nullable=True))
    op.add_column('enrollments', sa.Column('semester_1_completion_date', sa.Date(), nullable=True))
    op.add_column('enrollments', sa.Column('semester_2_completion_date', sa.Date(), nullable=True))
    op.alter_column('enrollments', 'enrollment_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('enrollments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='One of: active, completed, withdrawn, transferred')
    op.alter_column('enrollments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_enrollments_academic_year', table_name='enrollments')
    op.drop_index('ix_enrollments_grade', table_name='enrollments')
    op.drop_index('ix_enrollments_section', table_name='enrollments')
    op.create_foreign_key(None, 'enrollments', 'academic_years', ['academic_year_id'], ['id'])
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('notifications', 'updated_at')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               comment="Whether this is the user's first login",
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'password_expiry_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date when the password expires',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_expiry_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date when the password expires',
               existing_nullable=True)
    op.alter_column('users', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="Whether this is the user's first login",
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_index('ix_enrollments_section', 'enrollments', ['section'], unique=False)
    op.create_index('ix_enrollments_grade', 'enrollments', ['grade'], unique=False)
    op.create_index('ix_enrollments_academic_year', 'enrollments', ['academic_year'], unique=False)
    op.alter_column('enrollments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('enrollments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='One of: active, completed, withdrawn, transferred')
    op.alter_column('enrollments', 'enrollment_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('enrollments', 'semester_2_completion_date')
    op.drop_column('enrollments', 'semester_1_completion_date')
    op.drop_column('enrollments', 'semester_2_status')
    op.drop_column('enrollments', 'semester_1_status')
    op.drop_column('enrollments', 'semester')
    op.drop_column('enrollments', 'academic_year_id')
    # REMOVE THESE LINES from the downgrade function:
    # op.create_table('tenants', ...)
    # op.create_table('tenant_settings', ...)
    # op.create_table('resources', ...)
    # op.create_table('activity_logs', ...)
    
    op.drop_table('academic_years')
    # ### end Alembic commands ###