"""
refactor_fee_structure_to_grade_level

Revision ID: b4b19a40e0c9
Revises: d49807be9d94
Create Date: 2026-03-11 10:58:06.059048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4b19a40e0c9'
down_revision = 'd49807be9d94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_structures', sa.Column('grade_id', sa.UUID(), nullable=True))
    op.drop_constraint('fee_structures_class_id_fkey', 'fee_structures', type_='foreignkey')
    op.create_foreign_key(None, 'fee_structures', 'academic_grades', ['grade_id'], ['id'])
    op.drop_column('fee_structures', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_structures', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fee_structures', type_='foreignkey')
    op.create_foreign_key('fee_structures_class_id_fkey', 'fee_structures', 'classes', ['class_id'], ['id'])
    op.drop_column('fee_structures', 'grade_id')
    # ### end Alembic commands ###