"""
add_class_enrollment_and_update_relationships

Revision ID: b8f3abdb7e10
Revises: 9fba10beddbd
Create Date: 2025-09-17 18:59:02.703371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f3abdb7e10'
down_revision = '9fba10beddbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_enrollments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('drop_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id', 'academic_year_id', name='unique_student_class_year')
    )
    op.create_index(op.f('ix_class_enrollments_tenant_id'), 'class_enrollments', ['tenant_id'], unique=False)
    op.alter_column('attendances', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('unique_student_class_date_attendance', 'attendances', ['student_id', 'class_id', 'date'])
    op.add_column('classes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('enrollments', sa.Column('grade_id', sa.UUID(), nullable=False))
    op.add_column('enrollments', sa.Column('section_id', sa.UUID(), nullable=False))
    op.alter_column('enrollments', 'academic_year_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('enrollments', 'academic_year',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('enrollments', 'grade',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('enrollments', 'section',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_foreign_key(None, 'enrollments', 'grades', ['grade_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'sections', ['section_id'], ['id'])
    op.drop_column('students', 'grade')
    op.drop_column('students', 'section')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('section', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('grade', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.alter_column('enrollments', 'section',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('enrollments', 'grade',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('enrollments', 'academic_year',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('enrollments', 'academic_year_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('enrollments', 'section_id')
    op.drop_column('enrollments', 'grade_id')
    op.drop_column('classes', 'description')
    op.drop_constraint('unique_student_class_date_attendance', 'attendances', type_='unique')
    op.alter_column('attendances', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_class_enrollments_tenant_id'), table_name='class_enrollments')
    op.drop_table('class_enrollments')
    # ### end Alembic commands ###