"""
rename_county_column_to_lowercase

Revision ID: bad513ad5499
Revises: cfd7879ead10
Create Date: 2025-08-25 13:12:06.134954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad513ad5499'
down_revision = 'cfd7879ead10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('county', sa.String(length=100), nullable=True))
    op.drop_column('students', 'County')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('County', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('students', 'county')
    # ### end Alembic commands ###