"""
model updates for parent

Revision ID: bafc311a4bfc
Revises: ff43b3f14110
Create Date: 2025-08-25 14:32:51.063438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafc311a4bfc'
down_revision = 'ff43b3f14110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('parent_address', sa.String(length=255), nullable=True))
    op.drop_column('parents', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('parents', 'parent_address')
    # ### end Alembic commands ###