"""
updates schedules, class_model and timetable

Revision ID: cc964b0e1503
Revises: 39184320e931
Create Date: 2025-08-28 14:20:11.087599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc964b0e1503'
down_revision = '39184320e931'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###