"""
Add inactive status to teacher model

Revision ID: cfd7879ead10
Revises: 30940129a01c
Create Date: 2025-08-15 11:20:31.408695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd7879ead10'
down_revision = '30940129a01c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='One of: active, inactive, retired, resigned',
               existing_comment='One of: active, retired, resigned',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='One of: active, retired, resigned',
               existing_comment='One of: active, inactive, retired, resigned',
               existing_nullable=False)
    # ### end Alembic commands ###