"""
remove is_ative function from student model

Revision ID: d4f800d3dad6
Revises: bad513ad5499
Create Date: 2025-08-25 13:20:44.881152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f800d3dad6'
down_revision = 'bad513ad5499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###