"""
model update for user, student, teacher and parent

Revision ID: ff43b3f14110
Revises: 886bcee22b82
Create Date: 2025-08-25 14:27:24.358645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff43b3f14110'
down_revision = '886bcee22b82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_address', sa.String(length=255), nullable=True))
    op.drop_column('students', 'address')
    op.add_column('teachers', sa.Column('teacher_address', sa.String(length=255), nullable=True))
    op.drop_column('teachers', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('teachers', 'teacher_address')
    op.add_column('students', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('students', 'student_address')
    # ### end Alembic commands ###