'use client';

import { useState, useEffect } from 'react';
import { Tenant } from '@/types/tenant';
import { Eye, EyeOff, Copy, Check, AlertTriangle, Download, Shield } from 'lucide-react';

interface CredentialDisplayProps {
  tenant: Tenant;
  credentials: {
    email: string;
    password: string;
    username: string;
    tenantLoginUrl: string;
    userId: string;
  };
  onComplete: () => void;
  onBack: () => void;
}

export default function CredentialDisplay({ 
  tenant, 
  credentials, 
  onComplete, 
  onBack 
}: CredentialDisplayProps) {
  const [showPassword, setShowPassword] = useState(false);
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [timeRemaining, setTimeRemaining] = useState(300); // 5 minutes
  const [acknowledged, setAcknowledged] = useState(false);

  // Auto-hide timer
  useEffect(() => {
    const timer = setInterval(() => {
      setTimeRemaining(prev => {
        if (prev <= 1) {
          onComplete(); // Auto-complete when time runs out
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [onComplete]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const copyToClipboard = async (text: string, field: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(field);
      setTimeout(() => setCopiedField(null), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      setCopiedField(field);
      setTimeout(() => setCopiedField(null), 2000);
    }
  };

  const downloadCredentials = () => {
    const credentialText = `
TENANT ADMINISTRATOR CREDENTIALS
=====================================

Tenant: ${tenant.name}
Tenant Code: ${tenant.code}
Login URL: ${credentials.tenantLoginUrl}

ADMIN USER DETAILS:
User ID: ${credentials.userId}
Username/Email: ${credentials.email}
Temporary Password: ${credentials.password}

IMPORTANT SECURITY NOTES:
- This password was auto-generated by the system
- The admin user MUST change this password immediately upon first login
- Do not share these credentials via insecure channels (email, chat, etc.)
- Ensure the recipient changes the password during their first login session
- Delete this file after the credentials have been securely communicated
- The user will be prompted to change their password on first login

Generated on: ${new Date().toLocaleString()}
Generated by: Super Administrator

For security reasons, this information should only be accessible to authorized personnel.
    `;
    
    const blob = new Blob([credentialText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${tenant.code}-admin-credentials-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6">
      {/* Security Warning */}
      <div className="bg-amber-50 border border-amber-200 rounded-md p-4 mb-6">
        <div className="flex items-start">
          <AlertTriangle className="h-5 w-5 text-amber-600 mt-0.5 mr-3 flex-shrink-0" />
          <div>
            <h3 className="text-sm font-medium text-amber-800 mb-1">
              Security Notice - Auto-Hide in {formatTime(timeRemaining)}
            </h3>
            <p className="text-sm text-amber-700">
              These credentials are displayed only once and will auto-hide soon. The password was auto-generated by the backend system.
              Please copy them securely and communicate them to the tenant administrator through a secure channel.
            </p>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <div className="flex items-center mb-2">
          <Shield className="h-5 w-5 text-green-600 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900">
            Admin Credentials for {tenant.name}
          </h3>
        </div>
        <p className="text-sm text-gray-600">
          The admin account has been created successfully with an auto-generated secure password. 
          Please securely communicate these credentials to the tenant administrator.
        </p>
      </div>

      {/* Credentials Display */}
      <div className="space-y-4 mb-6">
        {/* User ID */}
        <div className="bg-gray-50 rounded-lg p-4">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            User ID
          </label>
          <div className="flex items-center space-x-2">
            <input
              type="text"
              value={credentials.userId}
              readOnly
              className="flex-1 px-3 py-2 bg-white border border-gray-300 rounded-md text-sm font-mono"
            />
            <button
              onClick={() => copyToClipboard(credentials.userId, 'userId')}
              className="p-2 text-gray-500 hover:text-gray-700 border border-gray-300 rounded-md hover:bg-gray-50"
              title="Copy User ID"
            >
              {copiedField === 'userId' ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
            </button>
          </div>
        </div>

        {/* Login URL */}
        <div className="bg-gray-50 rounded-lg p-4">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Login URL
          </label>
          <div className="flex items-center space-x-2">
            <input
              type="text"
              value={credentials.tenantLoginUrl}
              readOnly
              className="flex-1 px-3 py-2 bg-white border border-gray-300 rounded-md text-sm"
            />
            <button
              onClick={() => copyToClipboard(credentials.tenantLoginUrl, 'url')}
              className="p-2 text-gray-500 hover:text-gray-700 border border-gray-300 rounded-md hover:bg-gray-50"
              title="Copy URL"
            >
              {copiedField === 'url' ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
            </button>
          </div>
        </div>

        {/* Email/Username */}
        <div className="bg-gray-50 rounded-lg p-4">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Username/Email
          </label>
          <div className="flex items-center space-x-2">
            <input
              type="text"
              value={credentials.email}
              readOnly
              className="flex-1 px-3 py-2 bg-white border border-gray-300 rounded-md text-sm"
            />
            <button
              onClick={() => copyToClipboard(credentials.email, 'email')}
              className="p-2 text-gray-500 hover:text-gray-700 border border-gray-300 rounded-md hover:bg-gray-50"
              title="Copy Email"
            >
              {copiedField === 'email' ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
            </button>
          </div>
        </div>

        {/* Auto-Generated Password */}
        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
          <div className="flex items-center mb-2">
            <Shield className="h-4 w-4 text-green-600 mr-2" />
            <label className="block text-sm font-medium text-green-800">
              Auto-Generated Secure Password
            </label>
          </div>
          <div className="flex items-center space-x-2">
            <input
              type={showPassword ? 'text' : 'password'}
              value={credentials.password}
              readOnly
              className="flex-1 px-3 py-2 bg-white border border-green-300 rounded-md text-sm font-mono"
            />
            <button
              onClick={() => setShowPassword(!showPassword)}
              className="p-2 text-green-600 hover:text-green-800 border border-green-300 rounded-md hover:bg-green-100"
              title={showPassword ? 'Hide Password' : 'Show Password'}
            >
              {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
            </button>
            <button
              onClick={() => copyToClipboard(credentials.password, 'password')}
              className="p-2 text-green-600 hover:text-green-800 border border-green-300 rounded-md hover:bg-green-100"
              title="Copy Password"
            >
              {copiedField === 'password' ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
            </button>
          </div>
          <p className="text-xs text-green-700 mt-2">
            This password was automatically generated by the backend system and meets all security requirements.
          </p>
        </div>
      </div>

      {/* Download Option */}
      <div className="mb-6">
        <button
          onClick={downloadCredentials}
          className="flex items-center space-x-2 px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          <Download className="h-4 w-4" />
          <span>Download Credentials (Secure File)</span>
        </button>
        <p className="text-xs text-gray-500 mt-1">
          Downloads a text file with the credentials. Delete after secure communication.
        </p>
      </div>

      {/* Acknowledgment */}
      <div className="bg-blue-50 border border-blue-200 rounded-md p-4 mb-6">
        <div className="flex items-start">
          <input
            type="checkbox"
            checked={acknowledged}
            onChange={(e) => setAcknowledged(e.target.checked)}
            className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded mt-0.5 mr-3"
          />
          <div className="text-sm">
            <label className="font-medium text-blue-900">
              I acknowledge that I have securely copied these auto-generated credentials
            </label>
            <p className="text-blue-700 mt-1">
              I understand that these credentials should be communicated through a secure channel and that the recipient 
              will be required to change the password immediately upon first login.
            </p>
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex justify-between">
        <button
          type="button"
          onClick={onBack}
          className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          Back
        </button>
        
        <button
          onClick={onComplete}
          disabled={!acknowledged}
          className="px-6 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 disabled:bg-gray-400 disabled:cursor-not-allowed"
        >
          Complete Tenant Setup
        </button>
      </div>
    </div>
  );
}